# generates both halves of the audio thunk from the NDK's aaudio/AAudio.h.
#
# this is thunks/vulkan/gen-thunk.ps1 with a different regex, a different magic number and a
# different header. same rule: the two halves have to agree on a command id for every entry
# point, so they are generated together from one list, in one pass, and neither is hand-editable.
#
#   generated/aaudio_commands.inc             the host half's list. one AACMD(name) per line,
#                                             included several times with different definitions
#                                             of AACMD to build the id enum and the dispatch table.
#   generated/aaudio_protos.inc               the host half's types. one PFN_ typedef per command.
#   generated/aaudio_stubs.S                  the guest half. one x86-64 stub per command, each
#                                             16 bytes, in the same order.
#
# **the typedefs are generated, and vulkan's are not.** vulkan_core.h ships a PFN_ typedef for
# every command, so the vulkan generator only has to emit the *list* and the host template deduces
# the rest. AAudio.h ships none, and taking decltype(&AAudioStream_release) instead would drag in
# the header's availability attributes: the host layer builds at API 28 and eleven of these are
# __INTRODUCED_IN(29..36), so referencing the declarations is a diagnostic waiting to happen and
# linking against them is impossible. the typedef carries the signature and never names the symbol,
# which is also why the host half resolves everything with dlsym rather than -laaudio.
#
#   .\host\thunks\audio\gen-thunk.ps1

$ErrorActionPreference = "Stop"

$here = $PSScriptRoot
. (Join-Path $here "..\..\..\scripts\toolchain.ps1")
$tc = Resolve-Toolchain -Need Ndk
$NdkVersion = $tc.NdkRevision
$header = Join-Path $tc.NdkSysroot "usr\include\aaudio\AAudio.h"
$outDir = Join-Path $here "generated"

if (-not (Test-Path $header)) { throw "missing AAudio.h: $header" }
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

$text = Get-Content $header -Raw

# every entry point is declared exactly once, starting at the beginning of a line with AAUDIO_API
# and running to the first semicolon -- across as many lines as the prototype takes.
$blocks = [regex]::Matches($text, '(?ms)^AAUDIO_API\s+(.*?);')
if ($blocks.Count -eq 0) { throw "no AAUDIO_API declarations found in $header" }

$commands = [System.Collections.Generic.List[object]]::new()
$seen = @{}
foreach ($b in $blocks) {
    # one line, no nullability qualifiers, no availability attribute. _Nonnull and _Nullable are
    # clang extensions that mean nothing to a function pointer typedef, and __INTRODUCED_IN is the
    # whole reason these are typedefs rather than decltypes.
    $decl = $b.Groups[1].Value
    $decl = [regex]::Replace($decl, '__INTRODUCED_IN\s*\([^)]*\)', '')
    $decl = [regex]::Replace($decl, '\b_Nonnull\b|\b_Nullable\b', '')
    $decl = ($decl -split '\s+' | Where-Object { $_ -ne '' }) -join ' '

    # the first "(" is the parameter list: no return type contains the text AAudio, and no
    # parameter is a bare function pointer -- the three callbacks are named typedefs.
    $m = [regex]::Match($decl, '^(?<ret>.*?)\s*(?<name>AAudio\w+)\s*\((?<params>.*)\)$')
    if (-not $m.Success) { throw "could not parse declaration: $decl" }

    $name = $m.Groups['name'].Value
    if ($seen.ContainsKey($name)) { continue }
    $seen[$name] = $true
    $commands.Add([pscustomobject]@{
        Name   = $name
        Return = ($m.Groups['ret'].Value -replace '\s+\*', '*').Trim()
        Params = $m.Groups['params'].Value.Trim()
    })
}

# the magic syscall number. "SA" in the top 16 bits, the command id in the bottom 16 -- one range
# along from vulkan's 0x564B0000, deliberately distinct so the two stay decodable apart in a trace
# and in a crash. see host/src/audio_thunk.h.
$magic = 0x53410000
if ($commands.Count -ge 0xFFFF) { throw "too many commands for a 16-bit id" }

$banner = @"
// generated by host/thunks/audio/gen-thunk.ps1 from aaudio/AAudio.h, NDK $NdkVersion.
// $($commands.Count) entry points. do not edit; re-run the generator.
"@

# --- host half, the list -------------------------------------------------------------------
$inc = [System.Text.StringBuilder]::new()
[void]$inc.AppendLine($banner)
[void]$inc.AppendLine("// AACMD(name) is defined by the includer.")
foreach ($c in $commands) { [void]$inc.AppendLine("AACMD($($c.Name))") }
# AppendLine emits CRLF on windows and the here-strings in this file are LF, so the output would be
# mixed. everything in this repository is LF and .gitattributes enforces it; without this the
# committed generated files would come back modified after every run of the generator.
Set-Content -Path (Join-Path $outDir "aaudio_commands.inc") -Value $inc.ToString().Replace("`r`n", "`n") -Encoding ascii -NoNewline

# --- host half, the types ------------------------------------------------------------------
$proto = [System.Text.StringBuilder]::new()
[void]$proto.AppendLine($banner)
[void]$proto.AppendLine("// one function pointer type per entry point, so that the marshaller can deduce")
[void]$proto.AppendLine("// the signature without the header's declarations ever being referenced.")
foreach ($c in $commands) {
    [void]$proto.AppendLine("typedef $($c.Return) (*PFN_$($c.Name))($($c.Params));")
}
Set-Content -Path (Join-Path $outDir "aaudio_protos.inc") -Value $proto.ToString().Replace("`r`n", "`n") -Encoding ascii -NoNewline

# --- guest half --------------------------------------------------------------------------
# each stub is identical except for one immediate, which is the entire point: the host reads the
# guest's arguments out of the spilled CPUState, so no stub ever has to know its own signature.
# "mov %rcx, %r10" is there because the syscall instruction destroys RCX, which is where the C ABI
# put the fourth argument -- AAudioStream_write's timeout, as it happens.
#
# there is no attach call and no .init_array, unlike vulkan: nothing here has to resolve an entry
# point by index, because AAudio has no procedure-address API. the guest's own ld.so resolving
# these names is the whole mechanism.
$asm = [System.Text.StringBuilder]::new()
[void]$asm.AppendLine($banner)
[void]$asm.AppendLine(@"
// the stubs are emitted in command-id order and each is exactly 16 bytes, the same as vulkan's --
// not because anything indexes them, but because a disassembly of one is then a disassembly of
// all of them and an id is readable straight out of the immediate.

    .text
    .balign 16
    .globl __sharpemu_aaudio_stubs
    .hidden __sharpemu_aaudio_stubs
__sharpemu_aaudio_stubs:
"@)

$id = 0
foreach ($c in $commands) {
    $imm = "0x{0:X8}" -f ($magic + $id)
    [void]$asm.AppendLine(@"
    .balign 16
    .globl $($c.Name)
    .type $($c.Name),@function
$($c.Name):
    movq %rcx, %r10
    movl `$$imm, %eax
    syscall
    ret
    .size $($c.Name), .-$($c.Name)
"@)
    $id++
}

[void]$asm.AppendLine(@"
    .section .note.GNU-stack,"",@progbits
"@)

Set-Content -Path (Join-Path $outDir "aaudio_stubs.S") -Value $asm.ToString().Replace("`r`n", "`n") -Encoding ascii -NoNewline

Write-Host "$($commands.Count) entry points -> generated\aaudio_commands.inc, generated\aaudio_protos.inc, generated\aaudio_stubs.S"
Write-Host ("magic 0x{0:X8}" -f $magic)
