# generates both halves of the vulkan thunk from the NDK's vulkan_core.h.
#
# the two halves have to agree on a command id for every entry point, so they are generated
# together from one list, in one pass, and neither is hand-editable:
#
#   generated/vulkan_commands.inc              the host half. one VKCMD(name) per line, included
#                                              several times with different definitions of VKCMD
#                                              to build the id enum and the dispatch table.
#   generated/vulkan_stubs.S                   the guest half. one x86-64 stub per command, each
#                                              16 bytes, in the same order — so the host can find
#                                              any guest stub as base + 16 * id.
#
# the command list comes from the prototype declarations rather than from the PFN_ typedefs:
# vulkan_core.h has 633 PFN_ typedefs but only 623 commands, and the difference is callbacks
# (PFN_vkAllocationFunction, PFN_vkVoidFunction and friends) which are not entry points at all.
#
#   .\host\thunks\vulkan\gen-thunk.ps1

$ErrorActionPreference = "Stop"

$here = $PSScriptRoot
. (Join-Path $here "..\..\..\scripts\toolchain.ps1")
$tc = Resolve-Toolchain -Need Ndk
$NdkVersion = $tc.NdkRevision
$header = Join-Path $tc.NdkSysroot "usr\include\vulkan\vulkan_core.h"
$outDir = Join-Path $here "generated"

if (-not (Test-Path $header)) { throw "missing vulkan_core.h: $header" }
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

$text = Get-Content $header -Raw

$versionMatch = [regex]::Match($text, '#define\s+VK_HEADER_VERSION\s+(\d+)')
if (-not $versionMatch.Success) { throw "could not read VK_HEADER_VERSION from $header" }
$headerVersion = $versionMatch.Groups[1].Value

# every command is declared exactly once, at the start of a line, in this shape:
#   VKAPI_ATTR VkResult VKAPI_CALL vkCreateInstance(
$matches = [regex]::Matches($text, '(?m)^VKAPI_ATTR\s+([\w\*\s]+?)\s+VKAPI_CALL\s+(vk\w+)\s*\(')
$commands = [System.Collections.Generic.List[string]]::new()
$seen = @{}
foreach ($m in $matches) {
    $name = $m.Groups[2].Value
    if (-not $seen.ContainsKey($name)) {
        $seen[$name] = $true
        $commands.Add($name)
    }
}
if ($commands.Count -eq 0) { throw "no vulkan commands found in $header" }

# the magic syscall number. "VK" in the top 16 bits, the command id in the bottom 16 — see
# host/src/vulkan_thunk.h for why a syscall is the trap and why this range is free.
$magic = 0x564B0000
$attachId = 0xFFFF
if ($commands.Count -ge $attachId) { throw "too many commands for a 16-bit id" }

$banner = @"
// generated by host/thunks/vulkan/gen-thunk.ps1 from vulkan_core.h, VK_HEADER_VERSION $headerVersion.
// $($commands.Count) commands. do not edit; re-run the generator.
"@

# --- host half ---------------------------------------------------------------------------
$inc = [System.Text.StringBuilder]::new()
[void]$inc.AppendLine($banner)
[void]$inc.AppendLine("// VKCMD(name) is defined by the includer.")
foreach ($name in $commands) { [void]$inc.AppendLine("VKCMD($name)") }
# AppendLine emits CRLF on windows and the here-strings in this file are LF, so the output would be
# mixed. everything in this repository is LF and .gitattributes enforces it; without this the
# committed generated files would come back modified after every run of the generator.
Set-Content -Path (Join-Path $outDir "vulkan_commands.inc") -Value $inc.ToString().Replace("`r`n", "`n") -Encoding ascii -NoNewline

# --- guest half --------------------------------------------------------------------------
# each stub is identical except for one immediate, which is the entire point: the host reads
# the guest's arguments out of the spilled CPUState, so no stub ever has to know its own
# signature. "mov %rcx, %r10" is there because the syscall instruction destroys RCX, which is
# where the C ABI put the fourth argument — the same move every libc syscall wrapper makes.
$asm = [System.Text.StringBuilder]::new()
[void]$asm.AppendLine($banner)
[void]$asm.AppendLine(@"
// each stub is exactly 16 bytes and they are emitted in command-id order, so the host layer
// resolves any guest entry point as __sharpemu_vk_stubs + 16 * id. that is what lets
// vkGetInstanceProcAddr return an address the guest may actually call.

    .text
    .balign 16
    .globl __sharpemu_vk_stubs
    .hidden __sharpemu_vk_stubs
__sharpemu_vk_stubs:
"@)

$id = 0
foreach ($name in $commands) {
    $imm = "0x{0:X8}" -f ($magic + $id)
    [void]$asm.AppendLine(@"
    .balign 16
    .globl $name
    .type $name,@function
${name}:
    movq %rcx, %r10
    movl `$$imm, %eax
    syscall
    ret
    .size $name, .-$name
"@)
    $id++
}

# the attach call, run by the guest's own ld.so through .init_array as soon as the library is
# loaded. it hands the host the address of the stub table; nothing else can, because only the
# guest knows where its dynamic linker put us.
$attachImm = "0x{0:X8}" -f ($magic + $attachId)
[void]$asm.AppendLine(@"
    .balign 16
    .globl __sharpemu_vk_attach
    .hidden __sharpemu_vk_attach
    .type __sharpemu_vk_attach,@function
__sharpemu_vk_attach:
    leaq __sharpemu_vk_stubs(%rip), %rdi
    movl `$$attachImm, %eax
    syscall
    ret
    .size __sharpemu_vk_attach, .-__sharpemu_vk_attach

    .section .init_array,"aw",@init_array
    .balign 8
    .quad __sharpemu_vk_attach

    .section .note.GNU-stack,"",@progbits
"@)

Set-Content -Path (Join-Path $outDir "vulkan_stubs.S") -Value $asm.ToString().Replace("`r`n", "`n") -Encoding ascii -NoNewline

Write-Host "vulkan_core.h VK_HEADER_VERSION $headerVersion"
Write-Host "$($commands.Count) commands -> generated\vulkan_commands.inc, generated\vulkan_stubs.S"
Write-Host ("magic 0x{0:X8}, attach id 0x{1:X4}" -f $magic, $attachId)
